# Generated by Django 2.1 on 2018-08-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogspost',
            old_name='titel',
            new_name='title',
        ),
    ]
